language: 
  - python
  - cpp 
python:
  - "3.4"
  - "pypy"

before_install:
  - sudo apt-get install r-base
  - sudo apt-get install build-essential 
  - git clone https://github.com/lh3/seqtk.git
  - cd seqtk
  - make; sudo make install 
  - cd .. 
  - git clone https://github.com/torognes/vsearch.git
  - cd vsearch 
  - ./autogen.sh 
  - ./configure 
  - make 
  - sudo make install 
  - cd ..
  - cd database 
  - sh download_greengene.sh 
  - cd ..



install:
  - pip install -r requirements.txt 

script : 
  - snakemake -d working_directory -np final.biom --configfile config.yaml
