
---
# the Raw folder should contains fastq.gz file in format : <NAME>_1.fastq.gz and <NAME>_2.fastq.gz
raw_folder: raw

# Forward primers used for 16S
primer_forward: CCTACGGGAGGCAGCAG

# Reverse primers used for 16S
primer_reverse: CCGTCAATTCMTTTRAGT

# target 16s database database path. ( Greengene by default) 
database_fasta: ../database/gg_13_5.fasta.gz 
database_taxonomy: ../database/gg_13_5_taxonomy.txt.gz

# Scripts folder paths 
scripts_path: ../scripts        

# Mapping files 
sample_data: ../sample_data.tsv

# Taxonomic assignement threashold
threshold: 0.97

# Quality filtering. Remove reads bellow 
quality: 10

# Keep only <min> reads 
min_len: 400

# Keep only <max> reads 
max_len: 600

# minimum  size for global dereplication 
minuniquesize : 10

max_merge_diff: 5

# Merge tools <vsearch> or <flash>
merge_tool: vsearch 
