#!/bin/bash 

SAMPLE=$1 
DIR=data 

function percent 
{

echo "scale=2;$1/$2*100" |bc

}



RAW_READS_COUNT=$(zcat $DIR/raw/${SAMPLE}_1.fastq.gz|grep "@HWI"|wc -l)
MERGE_READS_COUNT=$(cat $DIR/${SAMPLE}.merged.fastq|grep "@HWI"|wc -l)
MERGE_READS_PERCENT=$(percent $MERGE_READS_COUNT $RAW_READS_COUNT)

CLEAN_READS_COUNT=$(cat data/${SAMPLE}.clean.fastq |grep "@HWI"|wc -l)
CLEAN_READS_PERCENT=$(percent $CLEAN_READS_COUNT $RAW_READS_COUNT)

FORWARD_CUTADAPT=$(cat data/${SAMPLE}.cutadapt_forward|grep "Reads written"|cut -d":" -f2|tr -d '[[:space:]]'|sed -e 's/(.*)//g'|tr -d ",")
REVERSE_CUTADAPT=$(cat data/${SAMPLE}.cutadapt_reverse|grep "Reads written"|cut -d":" -f2|tr -d '[[:space:]]'|sed -e 's/(.*)//g'|tr -d ",")

DEREP_MAX=$(head -n 1 data/${SAMPLE}.dereplicate.fasta|sed -re 's/.*size=([[:digit:]]*);/\1/g')


echo -e "raw\t$RAW_READS_COUNT\t100"
echo -e "merge\t$MERGE_READS_COUNT\t$(percent $MERGE_READS_COUNT $RAW_READS_COUNT)"
echo -e "clean\t$CLEAN_READS_COUNT\t$(percent $CLEAN_READS_COUNT $RAW_READS_COUNT)"

echo -e "forward\t$FORWARD_CUTADAPT\t$(percent $FORWARD_CUTADAPT $RAW_READS_COUNT)"
echo -e "reverse\t$REVERSE_CUTADAPT\t$(percent $REVERSE_CUTADAPT $RAW_READS_COUNT)"


# printf '%15s%15s\n' 'raw count' "$RAW_READS_COUNT"
# printf '%15s%15s\n' 'merge count' "$MERGE_READS_COUNT($MERGE_READS_PERCENT%)"
# printf '%15s%15s\n' 'clean count' "$CLEAN_READS_COUNT($CLEAN_READS_PERCENT%)"

# printf '%15s%15s\n' 'forward ' "$FORWARD_CUTADAPT"
# printf '%15s%15s\n' 'reverse ' "$REVERSE_CUTADAPT"

# printf '%15s%15s\n' 'derep max ' "$DEREP_MAX"




#=====================================
