#!/bin/bash 

DIR="data"
OUTPUT="all_report.txt"
echo -e "sample\traw\tmerge\tclean\t\forward\treverse" > $OUTPUT

for filename in $(ls $DIR/*.rename.fasta|cut -d "." -f1|uniq)
do 
echo $filename
sample=$(echo $filename|sed "s/$DIR\///g")
echo -e "$sample\t"$(./make_report $sample|cut -f2|paste -s -d"\t") >> $OUTPUT
done
