
---
# the Raw folder should contains fastq.gz file in format : <NAME>_1.fastq.gz and <NAME>_2.fastq.gz
raw_folder: raw


samples :
  - "1001"
  - "1003"
  # - "2101"
  # - "1082"
  # - "3039"
  # - "2332"
  # - "2303"
  # - "2309"
  # - "2061"
  # - "3152"
  # - "2325"
  # - "3203"
  # - "2086"
  # - "3284"
  # - "1429"
  # - "3133"
  # - "2052"
  # - "2315"
  # - "3209"
  # - "1400"
  # - "1015"
  # - "2170"
  # - "1086"
  # - "2003"
  # - "2345"
  # - "3007"
  # - "2428"
  # - "3167"
  # - "2058"
  # - "1353"
  # - "3026"
  # - "2203"
  # - "2321"
  # - "2395"
  # - "3131"
  # - "3165"
  # - "2104"
  # - "2019"
  # - "3125"
  # - "2344"
  # - "3025"
  # - "2423"
  # - "2372"
  # - "2397"
  # - "3017"
  # - "2375"
  # - "1078"
  # - "2407"
  # - "2296"
  # - "1117"
  # - "3104"
  # - "2042"
  # - "2382"
  # - "3147"
  # - "2346"
  # - "2100"
  # - "2179"
  # - "2120"
  # - "2123"
  # - "2316"
  # - "2012"
  # - "2069"
  # - "3143"
  # - "1106"
  # - "2378"
  # - "1222"
  # - "3050"
  # - "1039"
  # - "1511"
  # - "1262"
  # - "1036"
  # - "2006"
  # - "1219"
  # - "1029"
  # - "2112"
  # - "3080"
  # - "2323"
  # - "2096"
  # - "3265"
  # - "3270"
  # - "3239"
  # - "2065"
  # - "2030"
  # - "3151"
  # - "2122"
  # - "1111"
  # - "2082"
  # - "2311"
  # - "3127"
  # - "3061"
  # - "1048"
  # - "3098"
  # - "3102"
  # - "2351"
  # - "1080"
  # - "3092"
  # - "1177"
  # - "3155"
  # - "3256"
  # - "3086"
  # - "3022"
  # - "2180"
  # - "3158"
  # - "2060"
  # - "3126"
  # - "2208"
  # - "3032"
  # - "1001"
  # - "2007"
  # - "2206"
  # - "2148"
  # - "3252"
  # - "3210"
  # - "1037"
  # - "2124"
  # - "3162"
  # - "2178"
  # - "3292"
  # - "2027"
  # - "2182"
  # - "2015"
  # - "2145"
  # - "2153"
  # - "3004"
  # - "2432"
  # - "1090"
  # - "3230"
  # - "1107"
  # - "2306"
  # - "2205"
  # - "1148"
  # - "2051"
  # - "3009"
  # - "3136"
  # - "2041"
  # - "2140"
  # - "1096"
  # - "3181"
  # - "3258"
  # - "1284"
  # - "1270"
  # - "1053"
  # - "3089"
  # - "2176"
  # - "2070"
  # - "1126"
  # - "2193"
  # - "2029"
  # - "2115"
  # - "3111"
  # - "1530"
  # - "3202"
  # - "2171"
  # - "3123"
  # - "1103"
  # - "1043"
  # - "3036"
  # - "1042"
  # - "2001"
  # - "3048"
  # - "2049"
  # - "2056"
  # - "3043"
  # - "3208"
  # - "1003"
  # - "2299"
  # - "3145"
  # - "2327"
  # - "3247"
  # - "1383"
  # - "2347"
  # - "2131"
  # - "2154"
  # - "3232"
  # - "3053"
  # - "3118"
  # - "3067"
  # - "1193"
  # - "1091"
  # - "3182"
  # - "3064"
  # - "2005"
  # - "2080"
  # - "3257"
  # - "2135"
  # - "1075"
  # - "2149"
  # - "2210"


# Forward primers used for 16S
primer_forward: CCTACGGGAGGCAGCAG

# Reverse primers used for 16S
primer_reverse: CCGTCAATTCMTTTRAGT

# target 16s database database path. ( Greengene by default) 
database_fasta: ../database/gg_13_5.fasta.gz 
database_taxonomy: ../database/gg_13_5_taxonomy.txt.gz

# Scripts folder paths 
scripts_path: ../scripts        

# Mapping files 
sample_data: ../sample_data.tsv

# Taxonomic assignement threashold
threshold: 0.97

# Quality filtering. Remove reads bellow 
quality: 10

# Keep only <min> reads 
min_len: 400

# Keep only <max> reads 
max_len: 600

# minimum  size for global dereplication 
minuniquesize : 1

max_merge_diff: 5

# Merge tools <vsearch> or <flash>
merge_tool: flash 
